# -*- coding: utf-8 -*-
"""model buildung

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1948RxdIHFq73q6YylNPv-p24P8ugccK5
"""

import pandas as pd
df = pd.read_csv('/Salary_Dataset_DataScienceLovers.csv')
df.head()

import pandas as pd
df.info()

df.isnull().sum()

df['Company Name'].fillna(df['Company Name'].mode()[0], inplace=True)
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns (object type)
categorical_cols = df.select_dtypes(include='object').columns

# Apply Label Encoding to each categorical column
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

print("DataFrame after Label Encoding:")
display(df.head())

# Separate independent and dependent variables
X = df.drop('Salary', axis=1)
y = df['Salary']

print("Independent variables (X) head:")
display(X.head())

print("\nDependent variable (y) head:")
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""## Train and Evaluate Models

### 1. Linear Regression
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

# Make predictions
y_pred_lr = linear_reg_model.predict(X_test)

# Evaluate the model
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print(f"Linear Regression Mean Squared Error: {mse_lr:.2f}")
print(f"Linear Regression R-squared: {r2_lr:.2f}")

"""### 2. Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the model
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)

# Make predictions
y_pred_dt = decision_tree_model.predict(X_test)

# Evaluate the model
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"Decision Tree Mean Squared Error: {mse_dt:.2f}")
print(f"Decision Tree R-squared: {r2_dt:.2f}")

"""### 3. Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the model
random_forest_model = RandomForestRegressor(random_state=42)
random_forest_model.fit(X_train, y_train)

# Make predictions
y_pred_rf = random_forest_model.predict(X_test)

# Evaluate the model
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"Random Forest Mean Squared Error: {mse_rf:.2f}")
print(f"Random Forest R-squared: {r2_rf:.2f}")

"""### 4. Support Vector Machine (SVM) Regressor"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

# SVMs are sensitive to feature scaling, so we'll scale the data
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))

# Initialize and train the model
svm_model = SVR(kernel='rbf') # Using RBF kernel as a common choice
svm_model.fit(X_train_scaled, y_train_scaled.ravel())

# Make predictions and inverse transform
y_pred_svm_scaled = svm_model.predict(X_test_scaled)
y_pred_svm = scaler_y.inverse_transform(y_pred_svm_scaled.reshape(-1, 1))

# Evaluate the model
mse_svm = mean_squared_error(y_test, y_pred_svm)
r2_svm = r2_score(y_test, y_pred_svm)

print(f"SVM Mean Squared Error: {mse_svm:.2f}")
print(f"SVM R-squared: {r2_svm:.2f}")

"""### 5. K-Nearest Neighbors (KNN) Regressor"""

from google.colab import drive
drive.mount('/content/drive')

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the model
knn_model = KNeighborsRegressor(n_neighbors=5) # Using 5 neighbors as a starting point
knn_model.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mse_knn = mean_squared_error(y_test, y_pred_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print(f"KNN Mean Squared Error: {mse_knn:.2f}")
print(f"KNN R-squared: {r2_knn:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Create a DataFrame to store model performance metrics
model_performance = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVM', 'KNN'],
    'R-squared': [r2_lr, r2_dt, r2_rf, r2_svm, r2_knn]
})

# Sort by R-squared for better visualization
model_performance = model_performance.sort_values(by='R-squared', ascending=False)

# Create the bar plot
plt.figure(figsize=(12, 6))
sns.barplot(x='R-squared', y='Model', hue='Model', data=model_performance, palette='viridis', legend=False)
plt.title('Comparison of Model R-squared Scores')
plt.xlabel('R-squared Score')
plt.ylabel('Model')
plt.xlim(model_performance['R-squared'].min() - 0.1, model_performance['R-squared'].max() + 0.1) # Adjust x-axis limits for clarity
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

# Create a DataFrame to store model performance metrics for MSE
mse_performance = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'SVM', 'KNN'],
    'MSE': [mse_lr, mse_dt, mse_rf, mse_svm, mse_knn]
})

# Sort by MSE for better visualization (lower is better)
mse_performance = mse_performance.sort_values(by='MSE', ascending=True)

# Create the bar plot for MSE
plt.figure(figsize=(12, 6))
sns.barplot(x='MSE', y='Model', hue='Model', data=mse_performance, palette='viridis', legend=False)
plt.title('Comparison of Model Mean Squared Error (MSE)')
plt.xlabel('Mean Squared Error (MSE)')
plt.ylabel('Model')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""## Model Comparison Summary

From the evaluation metrics (R-squared and Mean Squared Error):

*   **SVM (Support Vector Machine)** appears to be the best performing model among those tested, exhibiting the highest R-squared score (0.08) and the lowest Mean Squared Error (approximately 3.75e+11). Although the R-squared is still very low, it indicates a slightly better fit compared to other models.

*   **Linear Regression** shows the second-best performance with an R-squared of 0.05 and an MSE of approximately 3.87e+11. Similar to SVM, the R-squared value is low, suggesting that a simple linear relationship might not fully capture the complexity of the data.

*   **K-Nearest Neighbors (KNN)**, **Random Forest Regressor**, and **Decision Tree Regressor** all performed poorly, indicated by their high Mean Squared Error values and negative R-squared scores. Negative R-squared values suggest that these models perform worse than simply predicting the mean of the target variable. This could be due to several factors, including the nature of the data, lack of feature engineering, or suboptimal hyperparameters.

**Conclusion:**

While SVM and Linear Regression showed marginally better performance than the other models, all models struggled to explain the variance in the 'Salary' feature, as indicated by the very low and negative R-squared values. This suggests that the current features or models might not be sufficient to accurately predict salaries in this dataset. Further feature engineering, exploration of more complex models, or hyperparameter tuning might be necessary to improve performance.
"""

import pickle

# Define the filename for the saved components
model_components_filename = 'svm_model_components.pkl'

# Package all necessary components into a dictionary
model_components = {
    'svm_model': svm_model,
    'scaler_X': scaler_X,
    'scaler_y': scaler_y,
    'label_encoders': label_encoders
}

# Save the dictionary to the file
with open(model_components_filename, 'wb') as file:
    pickle.dump(model_components, file)

print(f"All model components (SVM model, scalers, label encoders) saved as '{model_components_filename}'")

from google.colab import files

files.download('best_svm_model.pkl')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# 
# import streamlit as st
# import pandas as pd
# import pickle
# import numpy as np
# 
# # Load the model components
# try:
#     with open('svm_model_components.pkl', 'rb') as file:
#         model_components = pickle.load(file)
#     svm_model = model_components['svm_model']
#     scaler_X = model_components['scaler_X']
#     scaler_y = model_components['scaler_y']
#     label_encoders = model_components['label_encoders']
# except FileNotFoundError:
#     st.error("Error: 'svm_model_components.pkl' not found. Please ensure the model components are saved.")
#     st.stop()
# 
# # --- Streamlit App ----
# st.set_page_config(page_title="Salary Predictor", layout="centered")
# st.title("Salary Prediction with SVM")
# st.write("Enter the details below to predict the salary.")
# 
# # Input fields for features
# st.header("Job Details")
# 
# rating = st.slider("Rating", min_value=1.0, max_value=5.0, value=3.5, step=0.1)
# 
# # For categorical features, we need to handle them carefully.
# # Ideally, the Streamlit app would have dropdowns populated by unique values from the training data.
# # For simplicity, we'll ask for text input, but this assumes the user provides valid, known categories.
# # In a real-world scenario, you'd extract unique values from your original dataset to create these options.
# 
# # Placeholder for unique values - In a real app, these would be loaded from a config or pre-processed data
# # Since we don't have access to the original categorical values, we'll prompt for direct encoded values or use a simpler approach.
# # Let's assume for now, we're providing a list of most common ones or using an example.
# 
# # To make this robust, we should map the user input to the label encoder's known classes.
# # This would require saving the class list for each LabelEncoder.
# # For this demonstration, we'll assume the user provides a string that exists in the encoder's classes.
# 
# # For `Company Name`, `Job Title`, `Location`, `Employment Status`, `Job Roles`
# # We need the original unique values to create dropdowns for the user.
# # Since `label_encoders` contains fitted encoders, we can get their classes.
# 
# company_name_options = list(label_encoders['Company Name'].classes_)
# job_title_options = list(label_encoders['Job Title'].classes_)
# location_options = list(label_encoders['Location'].classes_)
# employment_status_options = list(label_encoders['Employment Status'].classes_)
# job_roles_options = list(label_encoders['Job Roles'].classes_)
# 
# company_name_input = st.selectbox("Company Name", options=company_name_options)
# job_title_input = st.selectbox("Job Title", options=job_title_options)
# salaries_reported = st.number_input("Salaries Reported", min_value=1, value=1)
# location_input = st.selectbox("Location", options=location_options)
# employment_status_input = st.selectbox("Employment Status", options=employment_status_options)
# jop_roles_input = st.selectbox("Job Roles", options=job_roles_options)
# 
# # Preprocess inputs
# def preprocess_input(rating, company_name_input, job_title_input, salaries_reported, location_input, employment_status_input, jop_roles_input):
#     # Create a DataFrame for the input
#     input_df = pd.DataFrame([[rating, company_name_input, job_title_input, salaries_reported, location_input, employment_status_input, jop_roles_input]],
#                             columns=['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'])
# 
#     # Apply Label Encoding using the loaded encoders
#     for col in ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']:
#         if col in label_encoders:
#             # Handle unseen labels by assigning a default value (e.g., -1 or the most frequent)
#             # For simplicity here, we assume inputs will be among known classes
#             try:
#                 input_df[col] = label_encoders[col].transform(input_df[col])
#             except ValueError:
#                 st.warning(f"Categorical value for '{col}' not recognized. Using a default encoded value.")
#                 input_df[col] = -1 # Or a more sophisticated handling
# 
#     # Scale numerical features (all features are numerical after encoding for X_train_scaled)
#     # The order of columns in X_train is crucial here.
#     # Ensure input_df columns match the order X was trained on.
#     # X.columns: Index(['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'], dtype='object')
# 
#     # Reorder columns to match the training data's X
#     X_cols = ['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles']
#     processed_input = scaler_X.transform(input_df[X_cols])
# 
#     return processed_input
# 
# if st.button("Predict Salary"):
#     processed_input = preprocess_input(rating, company_name_input, job_title_input, salaries_reported, location_input, employment_status_input, jop_roles_input)
# 
#     # Make prediction
#     predicted_salary_scaled = svm_model.predict(processed_input)
# 
#     # Inverse transform the scaled prediction to get actual salary
#     predicted_salary = scaler_y.inverse_transform(predicted_salary_scaled.reshape(-1, 1))[0][0]
# 
#     st.success(f"Predicted Salary: ₹{predicted_salary:,.2f}")
# 
# st.markdown("--- Developed for educational purposes --- ")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# pandas
# scikit-learn
# matplotlib
# seaborn
# streamlit
# numpy

from google.colab import files
files.download('requirements.txt')